FamilySchedule/Models/ViewModel/IndexRegistradoViewModel.cs
namespace FamilySchedule.Models.ViewModel
{
    public class IndexRegistradoViewModel
    {
        public Usuario Usuario { get; set; }
        public IEnumerable<NotificacionesModel> Notificaciones { get; set; } = new List<NotificacionesModel>();
    }
}

FamilySchedule/Controllers/EventoController.cs
using FamilySchedule.Migrations;
using FamilySchedule.Models;
using FamilySchedule.Models.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations.Internal;

namespace FamilySchedule.Controllers
{
    public class EventoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventoController(ApplicationDbContext context)
        {
            _context = context;
        }

        //metodo que retorna la lista de eventos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Eventos.ToListAsync());
        }

        //Metodos Get y post para crear un evento
        [HttpGet]
        public IActionResult Crear()
        {

            return PartialView("_Crear");
        }
        public async Task<IActionResult> Crear(EventArgs evento)
        {

            if (ModelState.IsValid)
            {
                _context.Add(evento);
                await _context.SaveChangesAsync();

                TempData["AlertMessage"] = "Evento Creado exitosamente";
                return Json(new { success = true, message = "Evento creado exitosamente." });
            }

            return PartialView("_Crear", evento);

        }

        //metodo que valida que el evento que se edite exista mediante el id
        public async Task<IActionResult> Editar(int id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var eventInfoFound = await _context.Eventos.FindAsync(id);

            if(eventInfoFound == null)
            {
                return NotFound();
            }

            return View(eventInfoFound);
        }

        //metodo que edita
        [HttpPost]
        public async Task<IActionResult> Editar(EventoModel evento)
        {
            if (ModelState.IsValid)
            {
                var eventoEncontrado = await _context.Eventos.FindAsync(evento.Id);
                if(eventoEncontrado != null)
                {
                    eventoEncontrado.Titulo = evento.Titulo;
                    eventoEncontrado.Creador = evento.Creador;
                    eventoEncontrado.Fecha = evento.Fecha;
                    eventoEncontrado.Descripcion = evento.Descripcion;

                    _context.Update(eventoEncontrado);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Evento Actualizado exitosamente";
                    return RedirectToAction("Index");
                    
                }
            }

            return NotFound();
        }

        public async Task<IActionResult> Eliminar(int id)
        {
            if (ModelState.IsValid)
            {
                var eventoEncontrado = await _context.Eventos.FindAsync(id);

                if (eventoEncontrado == null || id == null)
                {
                    return NotFound();
                }             
                   
                _context.Eventos.Remove(eventoEncontrado);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Evento Eliminado exitosamente";

                return RedirectToAction("Index");

            }
            
            return NotFound();
        }

        public async Task<IActionResult> GetEventos()
        {
            var eventos = await _context.Eventos
                .Select(e => new {
                    id = e.Id,
                    title = e.Titulo,
                    start = e.Fecha.ToString("yyyy-MM-ddTHH:mm:ss"), // Formato ISO 8601
                    description = e.Descripcion
                }).ToListAsync();
            return Json(eventos);
        }

    }
}

FamilySchedule/Controllers/Registrado/RelacionDeCuentasController.cs
using Microsoft.AspNetCore.Mvc;

namespace FamilySchedule.Controllers.Registrado
{
    public class RelacionDeCuentasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


    }
}

FamilySchedule/Views/registrado/BuscarFamiliares.cshtml
@model FamilySchedule.Models.Usuario

<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - FSchedule</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/FamilySchedule.styles.css" asp-append-version="true" />

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<body>



    <!--Add family member-->

    <form class="formContainer" asp-action="MainUser" method="post">

        <h1>FamilySchedule</h1>
        <h2>Agrega miembros a tu familia</h2>

        <div class="inpContainer">

            <input type="email" name="correoUsuarioInvitado" class="inp form-control" placeholder="Correo" aria-label="" aria-describedby="basic-addon2">
           
            <button type="submit" class="btnSubmit btn btn-primary">Enviar invitacion</button>
        </div>
    </form>

    <!-- sweetAlert-->
    @if (TempData["AlertMessage"] != null)
    {
        <script>
            Swal.fire({
                title: 'Invitacion enviada correctamente!',
                text: '@TempData["AlertMessage"]',
                icon: 'success'
            });
        </script>
    }

    @if (TempData["noNull"] != null)
    {
        <script>
            Swal.fire({
                position: "top-end",
                icon: "info",
                text: '@TempData["noNull"]',
                showConfirmButton: false,
                timer: 3500
            });
        </script>
    }
    @if (TempData["agrupado"] != null)
    {
        <script>
            Swal.fire({
                position: "top-end",
                icon: "info",
                text: '@TempData["agrupado"]',
                showConfirmButton: false,
                timer: 3500
            });
        </script>
    }
    @if (TempData["InvitacionFallida"] != null)
    {
        <script>
            Swal.fire({
                title: "AVISO!",
                text: "@TempData["InvitacionFallida"]",
                icon: "warning",
                confirmButtonText: 'OK D:'
            });
        </script>
    }
    @if (TempData["errorInvitacion"] != null)
    {
        <script>
            Swal.fire({
                title: "ERROR!",
                text: "@TempData["ErrorInvitacion"]",
                icon: "error",
                confirmButtonText: 'OK D:'
            });
        </script>
    }
    @if (TempData["MismoCorreo"] != null)
    {
        <script>
    Swal.fire({
    position: "top-end",
    icon: "error",
    title: "@TempData["MismoCorreo"]",
    showConfirmButton: false,
    timer: 2500
        });
      </script>
    }
    
    <!-- #endregion -->
    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }


    <link rel="stylesheet" href="~/css/buscarFamiliares.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

FamilySchedule/Views/registrado/IndexRegistrado.cshtml
@model FamilySchedule.Models.ViewModel.EventoNotificacionesViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FSchedule</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/FamilySchedule.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="position-fixed end-0 translate-middle-y p-3">
        <h2 class="notificationTitle">Notificaciones</h2>

        @if (Model.Notificaciones != null && Model.Notificaciones.Any())
        {
            <ul class="list-group">
                @foreach (var notificaciones in Model.Notificaciones)
                {
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <strong>@notificaciones.Mensaje</strong>
                        <div class="btn-group">
                            <a asp-action="AceptarInvitacion" asp-route-id="@notificaciones.Id" class="btn btn-primary btn-sm">Aceptar</a>
                            <a asp-action="RechazarInvitacion" asp-route-id="@notificaciones.Id" class="btn btn-danger btn-sm">Rechazar</a>
                        </div>
                    </li>
                }
            </ul>
        }
        else
        {
            <p><strong>No tienes notificaciones pendientes</strong></p>
        }
    </div>

    <div class="d-flex justify-content-center gap-3 p-3 bg-light rounded shadow">
        <a onclick="showInPopup('@Url.Action("Crear", "Evento", new { id = 0 }, Context.Request.Scheme)', '')" class="btn btn-sm btn-primary text-white">
            <i class="oi oi-plus"></i> Agregar un evento
        </a>
        <a href="@Url.Action("Crear", "Evento")" class="btn btn-outline-primary">Planear Evento</a>
        <a href="#" class="btn btn-outline-primary">Asignar Tarea</a>
        <a href="#" class="btn btn-outline-primary">Family Schedule</a>
        <a href="@Url.Action("cerrarSeccion", "Registrado")" class="btn btn-danger">
            <i class="fa-solid fa-door-closed"></i> Cerrar Sesión
        </a>
    </div>



        <div class="card mt-4">
            <div class="card-header text-center">
                <h5>Lista de Eventos</h5>
            </div>


            <div class="table-responsive">
                <table id="evento" class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Evento.FirstOrDefault().Titulo)</th>
                            <th>@Html.DisplayNameFor(model => model.Evento.FirstOrDefault().Fecha)</th>
                            <th>@Html.DisplayNameFor(model => model.Evento.FirstOrDefault().Creador)</th>
                            <th>@Html.DisplayNameFor(model => model.Evento.FirstOrDefault().Descripcion)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Evento)
                        {
                            <tr>
                                <td><strong>@Html.DisplayFor(modelItem => item.Titulo)</strong></td>
                                <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
                                <td>@Html.DisplayFor(modelItem => item.Creador)</td>
                                <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
                                <td>
                                    <a onclick="showInPopup('@Url.Action("Edit", "Eventos", new { id = item.Id }, Context.Request.Scheme)' ,'')" class="btn btn-outline-warning btn-sm"><i class="oi oi-pencil"></i> Editar</a>
                                    <button data-id="@item.Id" class="btn btn-outline-danger btn-sm deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="oi oi-trash"></i> Eliminar</button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

   

   
    <partial name="_MostrarModal" /> 
   <partial name="ModalEliminar" /> 

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Eventos/Delete/', false);
    </script>

    @if (TempData["InicioAlert"] != null)
    {
        <script>
            window.onload = function() {
                Swal.fire({
                    title: "¿Quieres agregar a los miembros de tu familia?",
                    text: "Agrega a tu grupo personalizado para utilizar las funciones de Family Schedule",
                    icon: "warning",
                    showCancelButton: true,
                    cancelButtonText: "Más tarde",
                    cancelButtonColor: "#d33",
                    confirmButtonColor: "#3085d6",
                    confirmButtonText: "¡Sí!"
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = '@Url.Action("BuscarFamiliares", "registrado")';
                    }
                });
            };
        </script>
    }
    @if (TempData["AlertMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["AlertMessage"]
        </div>
    }

    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/ShowModal.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="~/css/UsuarioStyle.css" asp-append-version="true" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.5/sweetalert2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

FamilySchedule/Views/registrado/ModalEliminar.cshtml
<div class="modal fade in" id="deleteDialog" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-blue-gradient">
                <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
            </div>
            <div class="modal-body">
                <p>¿Estas seguro de querer borrar este registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"> </i> No</button>
                <button type="button" class="btn btn-danger" id="btnYesDelete"><i class="fa fa-check-circle"> </i> Sí</button>
            </div>
        </div>
    </div>
</div>

FamilySchedule/Views/registrado/_MostrarModal.cshtml
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss=" modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>